version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports: ["3307:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./server
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports: ["3001:3001"]          # host 3001 → container 3001
    depends_on: [mysql]

  frontend:
    build: ./client/my-app        # uses the Nginx Dockerfile above
    environment:
      REACT_APP_API_URL: http://localhost:3001   # or delete if you call relative paths
    ports:
      - "80:80"
      - "443:80"
    depends_on: [backend]

volumes:
  mysql_data:
