version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST:     '%'
    ports: ["3307:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./server
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports: ["3001:3001"]
    depends_on: [mysql]

  frontend:
    build: ./client/my-app
    environment:
      # inside the container, “backend” resolves to the API container
      REACT_APP_API_URL: http://backend:3001
    ports:
      - "80:80"                # public HTTP
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

volumes:
  mysql_data:
  letsencrypt:
    external: true
